"""Add User model

Revision ID: 06579c4ed944
Revises: aa3edcd92297
Create Date: 2025-12-17 21:45:57.661536

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06579c4ed944'
down_revision: str | Sequence[str] | None = 'aa3edcd92297'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_projects_owner_id_users'), 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_owner_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
