"""add project ownership

Revision ID: abb290895e46
Revises: 06579c4ed944
Create Date: 2025-12-17 21:46:58.716250

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'abb290895e46'
down_revision: str | Sequence[str] | None = '06579c4ed944'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
